apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fulcio-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fulcio-server
    app.kubernetes.io/part-of: fulcio
  name: fulcio-servermo6e
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fulcio-server
    weight: 100
status: {}
