apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fulcio-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fulcio-server
    app.kubernetes.io/part-of: fulcio
  name: fulcio-server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: fulcio-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fulcio-server
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/fulcio/fulcio-server@sha256:23c064db2ba094056f3b173bf8789d49fc06d52e566bbff0bc75f2ae5e2559bd
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
