apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fulcio-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fulcio-server
    app.kubernetes.io/part-of: fulcio
  name: fulcio-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: fulcio-server
status:
  loadBalancer: {}
